[package]
name = "seed-network-server-common"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
tokio = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
