pub use handshaking_packets_mapping_system::handshaking_packets_mapping_system;
pub use login_packets_mapping_system::login_packets_mapping_system;
pub use play_packets_mapping_system::play_packets_mapping_system;
pub use status_packets_mapping_system::status_packets_mapping_system;

mod handshaking_packets_mapping_system;
mod login_packets_mapping_system;
mod play_packets_mapping_system;
mod status_packets_mapping_system;
