[package]
name = "seed-rs"
version = "0.1.0"
edition = "2021"
description = "Seed-RS"
authors = ["DooMWhite <doomwhitex@gmail.com>", "Ramon <ramonbernado.contato@gmail.com>"]
license = "MIT OR Apache-2.0"
