[package]
name = "seed-rs"
version = "0.2.0"
edition = "2021"
description = "Seed-RS"
authors = ["DooMWhite <doomwhitex@gmail.com>", "Ramon <ramonbernado.contato@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/ms-rusty/seed-rs"
