[package]
name = "seed-network-server"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
seed-network-common = { path = "../seed-network-common" }

anyhow = { workspace = true }
bevy = { workspace = true }
bevy-tokio-tasks = { workspace = true }
crossbeam-channel = { workspace = true }
tokio = { workspace = true }
