[package]
name = "seed"
version = "0.1.0"
edition = "2021"

[dependencies]
seed-game-world = { path = "../seed-game-world" }
seed-network-server = { path = "../seed-network-server" }

anyhow = { workspace = true }
bevy = { workspace = true }
tokio = { workspace = true }
