[package]
name = "seed-common"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
